// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjevkaxffguroyfypjkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqZXZrYXhmZmd1cm95Znlwamt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NTAxNTAsImV4cCI6MjA3NDAyNjE1MH0.IMjC-QVdpsf_iVu891syG7Q1HNu9Qfgmi18N7dT9eOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});